dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USERNAME') }}"  # Ce champ est requis
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
