dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: ${POSTGRES_HOST}  # Correction du nom de variable
      user: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
