name: Run Soda Scan on customers_certif

on:
  pull_request
permissions:
  contents: read
  pull-requests: write
  
jobs:
  soda_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Perform Soda Scan
        uses: sodadata/soda-github-action@main
        env:
         SODA_CLOUD_API_KEY: ${{ secrets.SODA_CLOUD_API_KEY }}
         SODA_CLOUD_API_SECRET: ${{ secrets.SODA_CLOUD_API_SECRET }}
         POSTGRES_HOST: ${{ secrets.POSTGRE_HOST }}  # Correction du nom de variable
         POSTGRES_USERNAME: ${{ secrets.POSTGRE_USERNAME }}
         POSTGRES_PASSWORD: ${{ secrets.POSTGRE_PASSWORD }}
        with:
          soda_library_version: v1.0.4
          data_source: customers_certif
          configuration: .github/soda/configuration.yml
          checks: .github/soda/checks.yml
