data_source customers_certif:
    type: postgres
    database: postgres
    schema: public
    env: 
        host: ${POSTGRES_HOST}  # Correction du nom de variable
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}

soda_cloud:
    # Use cloud.soda.io for EU region
    # Use cloud.us.soda.io for US region
    host: cloud.soda.io
    env:
        api_key_id: ${SODA_CLOUD_API_KEY}
        api_key_secret: ${SODA_CLOUD_API_SECRET}
